chemprop train \
    --output-dir train_output \
    --logfile train_output/log.txt \
    --data-path train.csv \
    --split-sizes 0.8 0.2 0.0 \
    --num-replicates 4 \
    --from-foundation CheMeleon \
    --pytorch-seed 42 \
    --smiles-columns SMILES \
    --target-columns "pEC50" "Emax_estimate (log2FC vs. baseline)" "pEC50_counter" "Emax_estimate (log2FC vs. baseline)_counter" \
    --task-type regression \
    --patience 5 \
    --init-lr 0.00001 \
    --warmup-epochs 5 \
    --loss mse \
    --metrics rmse r2 mse mae \
    --show-individual-scores \
    --ffn-num-layers 1 \
    --ffn-hidden-dim 512 \
    --batch-size 32 \
    --epochs 50
